RoomMap.Langs = {
	layers: 'Layers',
	levels: 'Levels',
	svginfo: 'Information about object',
	hidelayer: 'Hide layer',
	gocloser: 'Closer',
	goaway: 'Away',
	modes: 'Modes',
	mode_show: 'Show mode',
	mode_edit: 'Edit mode',
	add_circle: 'Add circle',
	add_polygon: 'Add polygon',
	edit_obj: 'Edit object',
	create: 'Create',
	save: 'Save',
	radius: 'Radius',
	coor_x: 'Coordinate X',
	coor_y: 'Coordinate Y',
	cancel: 'Cancel',
	createvis: 'Visual',
	new_object: 'New object',
	point: 'Point',
	removepoint: 'Remove this point'
	addpoint: 'Add point',
	editobject: 'Editing object',
	createobject: 'Creating new object',
	saveobject: 'Save',
	svgtitle: 'Title',
	svgdescription: 'Description'
}