RoomMap.Langs = {
	layers: 'Слои',
	levels: 'Уровни',
	svginfo: 'Информация об объекте',
	hidelayer: 'Скрыть слой',
	gocloser: 'Приблизить',
	goaway: 'Отдалить',
	modes: 'Режимы',
	mode_show: 'Режим просмотра',
	mode_edit: 'Режим редактирования',
	add_circle: 'Добавить окружность',
	add_polygon: 'Добавить полигон',
	edit_obj: 'Редактировать объект',
	create: 'Создать',
	save: 'Сохранить',
	radius: 'Радиус',
	coor_x: 'Координата X',
	coor_y: 'Координата Y',
	cancel: 'Отмена',
	createvis: 'Визуально',
	new_object: 'Новый объект',
	point: 'Точка',
	removepoint: 'Удалить точку',
	addpoint: 'Добавить точку',
	editobject: 'Редактирование объекта',
	createobject: 'Создание объекта',
	saveobject: 'Сохранить',
	svgtitle: 'Подсказка',
	svgdescription: 'Описание'
}